### ISSUE TITLE
Graphical styling

### ISSUE THREAD

**Issue by thoni56** [alan-if/alan-docs#3] opened 2018-08-22 10:02 UTC
One thing I don't know anything about, and is curious about, is graphical styling. In a sense, all AsciiDOC documents look the same. What are the possibilities of graphically styling the document? I'm thinking about typeface, page headers and other graphical elements, e.g. like what the DOC version of the manual now has.

Not that we need to exactly replicate the DOC, but curious, not only for this project, about the possibilities.

**Comment by tajmone** [comment] 2018-08-22 18:47
AsciiDoc gives us great freedom and control in how the final document will look like. Of course, much depends on how we're going to produce the final documents (ie, via AsciiDoc natively or using DocBook or other tools).

Usually, for ODT document format you provide a template document with all the styles defined it, and then make sure that the style name in the ADoc file and the template match, the rest is handled by the convertion tools.

I haven't actually converted from Asciidoctor to ODT as of now, but I had looked into it in the past, and it uses some common publishing standards shared by other workframes too. To use DocBook I'll have probably to switch all the work to the Ubuntu machine, for I recall that there were some problems doing it under Windows (this being the reason I hadn't experimented much with it in the past, but these problems might have now been solved). Also, the new WSL feature in Win 10 allows to use non-graphical Linux tools from within Windows, and having tested it I can say that it works quite well; so probably this could be a way to integrate DocBook into Windows without pains.

As for the HTML5 format, Asciidoctor already offers a number of templates, but if you look closely at them you'll notice that they use tables to create admonitions (like nots) instead of using divs! Can you believe it? There is a long thread on Asciidoctor abou this, the problem is that these templates date back to before the HTML5 transition, and they haven't been redesigned since. As mentioned before, Asciidoctor doesn't fair quite well with HTML5 out-of-the-box, and you only have to peak at the converted doc's source to witness the horrors of using tables for aligning element contents (but again, this is a left over from a time when this was still common practice). 

But Asciidoctor is flexible, and one can override the whole HTML5 templating system — I wouldn't say "easily" (as this requires some tedious work), but it can be done and its worth the effort (and it would also be a nice way to give back something to the Asciidoctor project, by sharing in open source a new HTML5 compliant template). Also, I believe that there are some nice and HTML5 compliant templates for Asciidoctor out there, just have to look for them.

Personally, I'm very interested in creating an executable eBook with all the Alan related documentation, a bit like the one available on Alan website (for Alan 2), but using a slightly more modern eBook compiler for it. I prefer executable ebooks to PDF documents because they can be navigate like website (no page breaks), allow multimediality, quick searching of the document, and are fully standalone. And they are better than CHM files because they allow good CSS styling and HTML5 contents under Windows.

So, I'm keen on investing energy on the HTML5 output, as this could also be used by an IDE application, to show the documentation via a WebBrowser control (which can then be highly customized via WinAPI). Also, I have a nice Sass template project I had been working on, which could serve well both the eBook as well as the online documentation on the website. Just need to put all the bits and pieces together.

**Comment by tajmone** [comment] 2018-08-26 13:54
> What are the possibilities of graphically styling the document? 

Yesterday I gave a quick look on how to convert from ADoc to PDF, and I've noticed that there are multiple solutions available.

### Asciidoctor PDF (YAML settings)

Right now, I'm using the [Asciidoctor PDF] gem, which I need to create a PDF file via the build scripts, because Asciidoctor doesn't build the Index for HTML docs, and I need to track how the Index reconstruction is going.

Having quickly glanced at the documentation of [Asciidoctor PDF], it seems that its driven by YAML settings files, which can be used to configure the styles and page setting of the final document. This looks interesting, especially since YAML is a good format when it comes to version control and collaboration.

### Pandoc (via LaTeX)

    Asciidoctor -> DocBook -> pandoc -> LaTeX

But there are other alternatives too. I was also thinking of pandoc, which uses the [LaTeX engine] to create PDF, and supports DocBook as input format — so, all we'd need to do is to first convert via Asciidoctor to DocBook, and then pipe the output to pandoc:

- [pandoc man: Creating a PDF]

LaTeX is also available for Windows OS in various editions:

- [MiKTeX]
- [proTeXt]
- [TeX Live]

I haven't yet looked into them, but I'm more than happy to explore them — having worked with book publishing in the past, it's a field I like and which I'm always eager to learn something new about.

### Pandoc (using ODT templates)

As I mentioned earlier, I recalled that pandoc has the added benefit of allowing to use ODT/DOCX documents as reference files or templates when converting to those formats. I think [this part of the pandoc documentation] mentions it:

> ```
> --reference-doc=FILE
>     Use the specified file as a style reference in producing a docx or ODT file.
> ```
> 
> For best results, the reference ODT should be a modified version of an ODT produced using pandoc. The contents of the reference ODT are ignored, but its stylesheets are used in the new ODT. [...]
> 
> To produce a custom "`reference.odt`", first get a copy of the default "`reference.odt`":
> 
>     pandoc --print-default-data-file reference.odt > custom-reference.odt 
> 
> Then open "`custom-reference.odt`" in LibreOffice, modify the styles as you wish, and save the file.

... this approach seems to offer an easy way to control how styles will look like in the final doc, since with LibreOffice style editing is WYSIWYG!


-------------------------------------------------------------------------------

Anyhow, I'm confident we'll come up with a good solution to control styling in the final document, so that the distributed PDF will look just great — and could even be used for publishing.

AsciiDoc having been around for a long time, there's definitely more than one way to "skin the cat", when it comes to producing PDF docs!


[this part of the pandoc documentation]: http://pandoc.org/MANUAL.html#options-affecting-specific-writers


[MiKTeX]: https://miktex.org/
[proTeXt]: http://www.tug.org/protext/
[TeX Live]: http://www.tug.org/texlive/
[pandoc man: Creating a PDF]: http://pandoc.org/MANUAL.html#creating-a-pdf

[Asciidoctor PDF]: https://github.com/asciidoctor/asciidoctor-pdf "Visit the Asciidoctor PDF repository"

[LaTeX engine]: https://www.latex-project.org/get/

**Comment by tajmone** [comment] 2018-09-05 22:35
We've finally worked out a solution for custom styling in PDF, so I'll close this and the conversation moves on in Issue #14 — where actual styles editing and proposal can be discussed.

**Closed by tajmone** 2018-09-05 22:35 UTC
